# Generated by Django 4.0.3 on 2022-03-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
                ('title', models.TextField()),
                ('raw_text', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('dictionary', models.TextField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
